### ISSUE TITLE
Exception when adding layer

### ISSUE THREAD

**Issue by m-kuhn** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#151] opened 2017-11-28 09:19 UTC
Just installed plugin, nothing else done.

Selected 3 layers: waterways, buildings, boundaries

Version 1.4.1

![screenshot from 2017-11-28 10-18-10](https://user-images.githubusercontent.com/588407/33311562-7556c216-d425-11e7-93a8-f4c7aeb31334.png)

```
An error has occurred while executing Python code: 

ValueError: dictionary update sequence element #0 has length 5; 2 is required 
Traceback (most recent call last):
  File "/home/mkuhn/.qgis2/python/plugins/vector_tiles_reader/ui/dialogs.py", line 565, in _load_tiles_for_connection
    selected_layers = dict(map(lambda i: self.model.item(i.row()).text(), indexes))
ValueError: dictionary update sequence element #0 has length 5; 2 is required
```

Python version: 2.7.14 (default, Nov  3 2017, 10:55:25) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] 
QGIS version: 2.18.13 Las Palmas, exported

**Comment by mnboos** [comment] 2017-11-28 09:38
Duplicate of #150

**Closed as completed by mnboos** 2017-11-28 09:38 UTC
