### ISSUE TITLE
Can't remove tiles

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#122] opened 2017-11-13 10:43 UTC
1. Add server tiles via plugin
2. Remove root tile group from layers list
3. Zoom

The tile group and its children reappear.

**Comment by mnboos** [comment] 2017-11-13 10:47
That's correct. The settings made in the connections dialog are the 'master'. That means, if you filter the layers to load there, by selecting one or more rows in the table, the plugin will always reload all layers. Otherwise, it will only reload the selected layers.

But maybe it would make sense, not to load a layer, if it's group has been removed. @sfkeller

**Comment by sfkeller** [comment] 2017-11-16 23:11
I'd also expect that when group is deleted, the layers should be deleted too. 
This issue seem to be a duplicate of #84 .

**Closed as completed by sfkeller** 2017-11-16 23:11 UTC
Labels: bug

**Comment by tomchadwin** [comment] 2017-11-16 23:17
Agreed - apologies.
