### ISSUE TITLE
Error object of type 'long' has no len() (Data? MacOS? Python version?)

### ISSUE THREAD

**Issue by cliffordsnow** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#67] opened 2017-06-14 02:06 UTC
FYI - Vector-Tiles-Reader-QGIS-Plugin runs find with QGIS 2.18.7 and python 2.7.10. It does not run with python 2.7.2.

**Comment by keum** [comment] 2017-06-14 02:09
This is log from python 2.7.2 
2017-06-13T19:05:56	0	Vector Tile Reader Plugin loaded...
2017-06-13T19:06:38	0	Decoding 110 tiles
2017-06-13T19:06:39	0	Processing 110 tiles
2017-06-13T19:06:39	2	An exception occured: object of type 'long' has no len()
2017-06-13T19:06:39	2	  File "/Users/peter/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 266, in _load_tiles
			    limit_reacher_handler=lambda: self._show_limit_exceeded_message(
			  File "/Users/peter/.qgis2/python/plugins/vector_tiles_reader/vt_reader.py", line 228, in load_tiles
			    self._process_tiles(tiles, layer_filter)
			  File "/Users/peter/.qgis2/python/plugins/vector_tiles_reader/vt_reader.py", line 316, in _process_tiles
			    self._create_geojson(tile, layer_filter)
			  File "/Users/peter/.qgis2/python/plugins/vector_tiles_reader/vt_reader.py", line 546, in _create_geojson
			    geojson_feature, geo_type = self._create_geojson_feature(feature, tile, extent)
			  File "/Users/peter/.qgis2/python/plugins/vector_tiles_reader/vt_reader.py", line 599, in _create_geojson_feature
			    all_out_of_bounds_func=lambda out_of_bounds: all_out_of_bounds.append(
			  File "/Users/peter/.qgis2/python/plugins/vector_tiles_reader/feature_helper.py", line 165, in map_coordinates_recursive
			    all_out_of_bounds_func=all_out_of_bounds_func))
			  File "/Users/peter/.qgis2/python/plugins/vector_tiles_reader/feature_helper.py", line 165, in map_coordinates_recursive
			    all_out_of_bounds_func=all_out_of_bounds_func))
			  File "/Users/peter/.qgis2/python/plugins/vector_tiles_reader/feature_helper.py", line 153, in map_coordinates_recursive
			    is_coordinate_tuple = len(coord) == 2 and all(isinstance(c, int) for c in coord)

**Comment by mnboos** [comment] 2017-06-14 04:45
@cliffordsnow Cool thanks for the info!

**Comment by mnboos** [comment] 2017-06-14 04:45
@keum That looks more than a problem with the source-data. What source exactly did you use (server or file, which server/file)?

**Comment by keum** [comment] 2017-06-14 14:07
@mnboos thanks for your answer. i've created three vector mbtiles and running on tileserver-gl . here is the link http://vectortile.pkgeo.com:8080/
Trying to add one of them but they've all failed to load. Thanks for your help. Should i open different tix?

**Comment by sfkeller** [comment] 2017-06-14 19:53
@keum: 
I can reproduce your error. It's probably related to the fact, that QGIS window is not centered around center and bounds of your MVT source.

So, I got at least "wabldg" (using this TileJSON http://vectortile.pkgeo.com:8080/data/wabldg.json) from your tileserver-gl working! 

Until we found a solution, first install two plugins using "Manage and Install Plugins" in QGIS: "QuickMapServices" (QMS) and "Quick Finder". 

Then each time you want to load your service (usually in a new QGIS project):
* Click on "QuickMapServices" icon and load OSM > "OSM Standard" in order to get a base map to see where we are in the QGIS window. 
* Zoom in anywhere (that's to prevent a "bug" in QMS, which centers but does not zoom in)
* In "Quick Finder" text intput field, type in the geographic name where the data of your service data is located (in case of "wabldg" it's "Greenwood, Seattle"). 
* Click on "Greenwood, Seattle" from the result list, so that the map zooms to it.
* Click on "Add Vector Tiles Layer" icon and register e.g. the TileJSON file of wabldg mentioned above. 
* Then click on "Connect" (service) and click on "Add" (layer) in "Add Vector Tiles Layer" dialog.

Done.

**Comment by sfkeller** [comment] 2017-06-14 19:57
@mnboos: 
This exception seems to be related to the fact that a (new?) QGIS window is located completely outside the data bounds of a service.
Does the MVT reader take the "bounds" (or "center") values of the TileJSON into account (see http://vectortile.pkgeo.com:8080/data/wabldg.json from above)?

**Comment by mnboos** [comment] 2017-06-15 05:22
@sfkeller What exception is logged to your console? I could also reproduce "an" error, but it's not the one @keum logged above. However, I'll try to fix it later today.

@keum Thank you for providing those sources, that's very helpful!

**Comment by sfkeller** [comment] 2017-06-15 07:23
I think this is the relevant log part from Vector Tile Reader log tab I refered to above:
2017-06-14T21:38:53	0	Decoding 96 tiles
2017-06-14T21:38:54	0	Import complete
2017-06-14T21:38:55	2	An exception occured: min() arg is an empty sequence
2017-06-14T21:38:55	2	  File "C:/Users/sfkeller/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 264, in _load_tiles
			    limit_reacher_handler=lambda: self._show_limit_exceeded_message(tile_limit))
			  File "C:/Users/sfkeller/.qgis2/python/plugins\vector_tiles_reader\vt_reader.py", line 236, in load_tiles
			    loaded_extent = {"x_min": min(loaded_tiles_x),

**Comment by mnboos** [comment] 2017-06-15 11:28
That's not actually the problem, only a result of it. The problem is, that there are no tiles available from the source, that match the visible QGIS extent.

**Comment by sfkeller** [comment] 2017-06-15 12:02
Agreed. Let me just collect some facts again (without suggesting a solution here yet):

Thanks to @keum we obviously have another service example which is not covering whole world (as e.g. OpenMapTiles), but only a region. 

There's an "Add Layer(s)" dialog implemented which takes the current "Map View" (*) into account - and that is not obvious to new users.

Then, from metadata (TileJSON entries or mbtiles metadata table) the reader knows "bounds" (and "center") values of the source.

(*) I'm admittedly nit-picking here, but be aware that IMHO officially it's called "Map View" according to "QGIS GUI Intro" (see #70), not "extent".

**Comment by mnboos** [comment] 2017-06-15 13:21
I fixed some bugs and it should work now. I would be happy if you both @keum and @sfkeller could test as soon as the plugin is approved in the QGIS plugin repository.

**Comment by keum** [comment] 2017-06-15 14:47
thanks @mnboos I've updated my mac last night which updated python to 2.7.10 from 2.7.2. I couldn't even get sample data to load and I'll test them out today with sample data plus my own mbtiles. Thanks for all your help!

**Comment by mnboos** [comment] 2017-06-15 19:26
@keum Okay, let me know, if there are any problems. I'm closing this issue as I think the problems are solved but feel free to reopen!

**Closed as completed by mnboos** 2017-06-15 19:26 UTC
Labels: bug
