### ISSUE TITLE
QGIS 3: 'ConnectionsDialog' object has no attribute 'connect'

### ISSUE THREAD

**Issue by saberraz** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#213] opened 2018-09-11 07:12 UTC
It is related to line 146 in dialog.py
self.btnConnectFile.clicked.connect(lambda: self.connect(self._mbtiles_conn))

To reproduce the error, install First Aid plugin and try to connect to a file based vector tile.

**Comment by sfkeller** [comment] 2018-09-11 07:15
Pls. add at least OS and QGIS version.

**Comment by saberraz** [comment] 2018-09-11 08:18
QGIS master, Ubuntu 18.04

**Comment by nevi-me** [comment] 2018-09-15 13:41
I can reproduce the same error on QGIS 3.2.1, Windows 10, by trying to load a .mbtiles file.

When clicking the Refresh button, I get:

```
An error has occurred while executing Python code: 

AttributeError: 'ConnectionsDialog' object has no attribute 'connect' 
Traceback (most recent call last):
  File "C:/Users/nevi_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\ui\dialogs.py", line 146, in 
    self.btnConnectFile.clicked.connect(lambda: self.connect(self._mbtiles_conn))
AttributeError: 'ConnectionsDialog' object has no attribute 'connect'


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.2.1-Bonn Bonn, 1edf372fb8 

Python Path:
D:/OSGeo4W64/apps/qgis/./python
C:/Users/nevi_/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/nevi_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/OSGeo4W64/apps/qgis/./python/plugins
D:\OSGeo4W64\bin\python36.zip
D:\OSGeo4W64\apps\Python36\DLLs
D:\OSGeo4W64\apps\Python36\lib
D:\OSGeo4W64\bin
D:\OSGeo4W64\apps\Python36
D:\OSGeo4W64\apps\Python36\lib\site-packages
D:\OSGeo4W64\apps\Python36\lib\site-packages\h5py-2.7.0-py3.6-win-amd64.egg
D:\OSGeo4W64\apps\Python36\lib\site-packages\win32
D:\OSGeo4W64\apps\Python36\lib\site-packages\win32\lib
D:\OSGeo4W64\apps\Python36\lib\site-packages\Pythonwin
C:/Users/nevi_/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\nevi_\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
```

**Comment by tomchadwin** [comment] 2018-09-16 08:15
Duplicate of #209?

**Comment by nevi-me** [comment] 2018-09-16 08:43
Probably, though the author talks about a First Aid plugin. Mine is a dupe of 209 yes

**Comment by tomchadwin** [comment] 2018-09-17 10:56
First Aid plugin is a remote debugger. Pretty sure this is therefore definitely a duplicate.

**Comment by mnboos** [comment] 2018-11-01 09:55
Closing as it's a duplicate of #209

**Closed as completed by mnboos** 2018-11-01 09:55 UTC
